- hosts: localhost
  gather_facts: false
  vars:
    error_msg: "error msg"
    success_msg: "no error found"
  tasks:
    - name: "1.1: Assert fail_msg not quiet"
      ignore_errors: true
      assert:
        quiet: false
        fail_msg: "{{ error_msg }}"
        that:
          false

    - name: "1.2: Assert fail_msg quiet"
      ignore_errors: true
      assert:
        quiet: true
        fail_msg: "{{ error_msg }}"
        that:
          false

    - name: "2.1: Assert success_msg"
      assert:
        quiet: false
        success_msg: "{{ success_msg }}"
        that:
          true

    - name: "2.2: Assert success_msg quiet"
      assert:
        quiet: true
        success_msg: "{{ success_msg }}"
        that:
          true

    - name: "3.1: Assert ok quiet"
      assert:
        quiet: true
        that:
          true

    - name: "3.2: Assert ok not quiet"
      assert:
        quiet: false
        that:
          true

    - name: "4.1: Assert change status"
      register: test_status
      assert:
        quiet: false
        that:
          true

    - name: "4.1: Show status"
      debug:
        var: test_status
