# optional ##
# optional ## X_RESOURCE_TYPE_X [/ X_RESOURCE_COMPONENT_X]
# optional ##

# X_TERRAFORM_RESOURCE_PLACEHOLDER_X
resource "X_TERRAFORM_RESOURCE_TYPE_X" "X_TERRAFORM_RESOURCE_NAME_X" {
  # X_TERRAFORM_RESOURCE_CONFIGURATION_PLACEHOLDER_X
}
