---
- name: "Prepare"
  hosts: "{{ lookup('env', 'APLATFORM64_TEST_PLATFORM') | default('all') }}"
  gather_facts: false
  tasks:

    - name: "Discover platform"
      ansible.builtin.setup:
        gather_subset: "min"
        gather_timeout: "10"
      changed_when: false

    - name: "Prepare"
      vars:
        X_ROLE_NAME_X:
          resolve_prereq: true
          prepare: true
      ansible.builtin.include_role:
        name: "X_ROLE_NAME_X"
...
