- hosts: localhost
  gather_facts: false

  tasks:
    - name: "1: Jinja code in set_fact"
      set_fact:
        generated_content: "
          {%- if
                false
          -%}
            {{ 'if False' }}
          {%- elif
            false
          -%}
            {{ 'elif False' }}
          {%- else -%}
            {{ 'else' }}
          {%- endif -%}
        "
    - name: "1: Show var"
      debug:
        var: generated_content

    - name: "2: Jinja code in task vars"
      vars:
        generated_content: "
          {%- if
                false
          -%}
            {{ 'if False' }}
          {%- elif
            false
          -%}
            {{ 'elif False' }}
          {%- else -%}
            {{ 'else' }}
          {%- endif -%}
        "
      debug:
        var: generated_content

    - name: "3: Jinja code in include_vars"
      include_vars:
        file: "vars.yml"

    - name: "3: Show var"
      debug:
        var: generated_content

    - name: "4: Jinja code in module parameter"
      debug:
        msg: "
          {%- if
                false
          -%}
            {{ 'if False' }}
          {%- elif
            false
          -%}
            {{ 'elif False' }}
          {%- else -%}
            {{ 'else' }}
          {%- endif -%}
        "
