user nginx;
worker_processes auto;
worker_cpu_affinity auto;

error_log /var/log/nginx/error.log warn;

include /etc/nginx/modules-enabled/*.conf;

events {
	worker_connections 512;
}

http {
	# X_HTTP_GLOBAL_PLACEHOLDER_X
	access_log /var/log/nginx/access.log main;

	include /etc/nginx/conf.d/*.conf;
	include /etc/nginx/sites-enabled/*;
}
