---
dependency:
  name: "galaxy"
  options:
    ignore-errors: true
    role-file: "meta/requirements-dev.yml"
    requirements-file: "meta/requirements-dev.yml"
    collections-path: ${APLATFORM64_CACHE_ANSIBLE}
driver:
  name: "podman"
lint: |
  set -e
  yamllint .
  ansible-lint -c ${APLATFORM64_ANSIBLE_LINT}
platforms:
  - name: "centos7"
    image: "docker.io/library/centos:7"
    pre_build_image: false
    groups:
      - "centos"
      - "redhat"
      - "rhel"
      - "linux"
  - name: "centos7-systemd"
    image: "docker.io/library/centos:7"
    tmpfs:
      - "/run"
      - "/tmp"
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    capabilities:
      - "SYS_ADMIN"
    command: "/usr/sbin/init"
    pre_build_image: false
    groups:
      - "centos"
      - "centos-systemd"
      - "redhat"
      - "redhat-systemd"
      - "rhel"
      - "rhel-systemd"
      - "linux"
      - "linux-systemd"
  - name: "centos8"
    image: "docker.io/library/centos:8"
    pre_build_image: false
    groups:
      - "centos"
      - "redhat"
      - "rhel"
      - "linux"
  - name: "centos8-systemd"
    image: "docker.io/library/centos:8"
    tmpfs:
      - "/run"
      - "/tmp"
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    capabilities:
      - "SYS_ADMIN"
    command: "/usr/sbin/init"
    pre_build_image: false
    groups:
      - "centos"
      - "centos-systemd"
      - "redhat"
      - "redhat-systemd"
      - "rhel"
      - "rhel-systemd"
      - "linux"
      - "linux-systemd"
  - name: "oraclelinux8"
    image: "docker.io/library/oraclelinux:8"
    pre_build_image: false
    groups:
      - oel
      - "redhat"
      - "rhel"
      - "linux"
  - name: "oraclelinux8-systemd"
    image: "docker.io/library/oraclelinux:8"
    tmpfs:
      - "/run"
      - "/tmp"
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    capabilities:
      - "SYS_ADMIN"
    command: "/usr/sbin/init"
    pre_build_image: false
    groups:
      - oel
      - oel-systemd
      - "redhat"
      - "redhat-systemd"
      - "rhel"
      - "rhel-systemd"
      - "linux"
      - "linux-systemd"
  - name: "ubuntu20"
    image: "docker.io/library/ubuntu:20.04"
    pre_build_image: false
    groups:
      - "ubuntu"
      - "linux"
  - name: "ubuntu20-systemd"
    image: "ghcr.io/serdigital64/ubuntu-20.4-systemd-full:0.1.0"
    tmpfs:
      - "/run"
      - "/tmp"
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    capabilities:
      - "SYS_ADMIN"
    command: "/usr/sbin/init"
    pre_build_image: false
    groups:
      - "ubuntu"
      - "ubuntu-systemd"
      - "linux"
      - "linux-systemd"
  - name: "ubuntu21"
    image: "docker.io/library/ubuntu:21.04"
    pre_build_image: false
    groups:
      - "ubuntu"
      - "linux"
  - name: "ubuntu21-systemd"
    image: "ghcr.io/serdigital64/ubuntu-21.4-systemd-full:0.1.0"
    tmpfs:
      - "/run"
      - "/tmp"
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    capabilities:
      - "SYS_ADMIN"
    command: "/usr/sbin/init"
    pre_build_image: false
    groups:
      - "ubuntu"
      - "ubuntu-systemd"
      - "linux"
      - "linux-systemd"
  - name: "fedora33"
    image: "fedora:33"
    pre_build_image: false
    groups:
      - "fedora"
      - "redhat"
      - "linux"
  - name: "debian10"
    image: "docker.io/library/debian:buster"
    pre_build_image: false
    groups:
      - "debian"
      - "linux"
  - name: "debian11"
    image: "docker.io/library/debian:bullseye"
    pre_build_image: false
    groups:
      - "debian"
      - "linux"
  - name: "rhel7"
    image: "registry.access.redhat.com/ubi7/ubi"
    pre_build_image: false
    groups:
      - "redhat"
      - "rhel"
      - "linux"
  - name: "rhel7-systemd"
    image: "registry.access.redhat.com/ubi7/ubi-init"
    tmpfs:
      - "/run"
      - "/tmp"
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    capabilities:
      - "SYS_ADMIN"
    command: "/usr/sbin/init"
    pre_build_image: false
    groups:
      - "redhat"
      - "redhat-systemd"
      - "rhel"
      - "rhel-systemd"
      - "linux"
      - "linux-systemd"
  - name: "rhel8"
    image: "registry.access.redhat.com/ubi8/ubi"
    pre_build_image: false
    groups:
      - "redhat"
      - "rhel"
      - "linux"
  - name: "rhel8-systemd"
    image: "registry.access.redhat.com/ubi8/ubi-init"
    tmpfs:
      - "/run"
      - "/tmp"
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    capabilities:
      - "SYS_ADMIN"
    command: "/usr/sbin/init"
    pre_build_image: false
    groups:
      - "redhat"
      - "redhat-systemd"
      - "rhel"
      - "rhel-systemd"
      - "linux"
      - "linux-systemd"
provisioner:
  name: "ansible"
verifier:
  name: "ansible"
...
