---
# Define supported platforms
X_ROLE_NAME_X_platforms:
  - "CentOS8"
  - "OracleLinux8"
  - "Ubuntu20"
  - "Ubuntu21"
  - "Fedora33"
  - "Fedora35"
  - "Debian10"
  - "Debian11"

# Group Linux Distributions by family
X_ROLE_NAME_X_os_family: "
  {%- if
      ( ansible_distribution == 'CentOS' ) or
      ( ansible_distribution == 'OracleLinux' ) or
      ( ansible_distribution == 'Fedora' )
  -%}
    {{ 'RedHat' }}
  {%- elif
      ( ansible_distribution == 'Debian' ) or
      ( ansible_distribution == 'Ubuntu' )
  -%}
    {{ 'Ubuntu' }}
  {%- else -%}
    {{ 'Linux' }}
  {%- endif -%}
  "

# TODO: Remove this snippet if not used
# Define default options. Used as a backup for cases where optional Ansible defaults are missing
# X_ROLE_NAME_X_server_presets:
#   X_PREDEFINED1_X: ""

# TODO: Remove this snippet if not used
# Define default options. Used as a backup for cases where optional Ansible defaults are missing
# X_ROLE_NAME_X_paths_presets:
#   X_DEFAULT_PATH_X: "X_DEFAULT_PATH_VALUE_X"

# TODO: Remove this snippet if not used
# Define default options. Used as a backup for cases where optional Ansible defaults are missing
# X_ROLE_NAME_X_firewall_presets:
#   zone: "public"

# Multiplatform packages
X_ROLE_NAME_X_profiles_common:
  snap: {}
  flatpak: {}
  pip: {}
  # TODO: Remove this snippet if not used
  # snap:
  #   latest:
  #     supported: true
  #     packages:
  #       - name: "X_APP_PACKAGE_X"
  # flatpak:
  #   latest:
  #     supported: true
  #     origin: "flathub"
  #     packages:
  #       - name: "X_APP_PACKAGE_X"
  # pip:
  #   latest:
  #     supported: true
  #     packages:
  #         - name: "X_APP_PACKAGE_X"
  #     options:
  #       pip:
  #         owner: "{{ X_ROLE_NAME_X_owners['X_DEFAULT_USER_X']['name'] }}"
  #         group: "{{ X_ROLE_NAME_X_owners['X_DEFAULT_USER_X']['group'] }}"
  #         path: "{{ X_ROLE_NAME_X_paths['X_DEFAULT_PATH_X'] }}"
  #         cli: "{{ X_ROLE_NAME_X_application['name'] }}"

# Define common paths
X_ROLE_NAME_X_base_common:
  access:
    user:
      owner: "root"
      # X_DEFAULT_USER_X: "{{ X_ROLE_NAME_X_owners['X_DEFAULT_USER_X']['name'] }}"
    group:
      owner: "root"
      # X_DEFAULT_USER_X: "{{ X_ROLE_NAME_X_owners['X_DEFAULT_USER_X']['group'] }}"
    mode:
      dir: "0755"
      file: "0644"
      exe: "0755"
  templates: {}
  paths: {}
  files: {}
  run: {}
  etc: {}
  # TODO: Remove this snippet if not used
  # templates:
  #   X_TEMPLATE_SERVER_X: "X_TEMPLATE_SERVER_NAME_X.j2"
  # paths:
  #   X_BASE_PATH_X: "{{ X_ROLE_NAME_X_paths['X_DEFAULT_PATH_X'] }}"
  #   X_BASE_PATH_X: "{{ X_ROLE_NAME_X_paths['X_DEFAULT_PATH_X'] | default(X_ROLE_NAME_X_paths_presets['X_DEFAULT_PATH_X']) }}"
  # files:
  #   X_BASE_FILE_SETUP_X: "X_BASE_FILE_SETUP_VALUE_X"
  # run:
  #   X_BASE_RUN_X: "X_BASE_RUN_VALUE_X"
  # etc:
  #   X_BASE_ETC_X: "X_BASE_ETC_VALUE_X"

# Build firewall rules based on end-state requirements
X_ROLE_NAME_X_firewall_rules:
  - id: "X_FWE_RULE"
    service: "X_FWE_SERVICE"
    # zone: "{{ X_ROLE_NAME_X_firewall['zone'] | default(X_ROLE_NAME_X_firewall_presets['zone']) }}"
    zone: "{{ X_ROLE_NAME_X_firewall['zone'] }}"
    allow: "{{ X_ROLE_NAME_X_subsystem['enabled'] | ternary('enabled', 'disabled') }}"

# Temporary loop variables
# X_ROLE_NAME_X___prepare_path
# X_ROLE_NAME_X___setup_user
...
