---
- name: "X_TASK_COLLECTION_NAME_X / X_TASK_ROLE_NAME_X / Prepare / Paths / Create"
  become: true
  ansible.builtin.file:
    follow: false
    force: false
    unsafe_writes: false
    recurse: false
    state: "directory"
    path: "{{ X_ROLE_NAME_X___prepare_path }}"
    owner: "{{ X_ROLE_NAME_X_base['access']['user']['owner'] }}"
    group: "{{ X_ROLE_NAME_X_base['access']['group']['owner'] }}"
    mode: "{{ X_ROLE_NAME_X_base['access']['mode']['dir'] }}"
  loop:
    - "{{ X_ROLE_NAME_X_base['paths']['X_BASE_PATH_X'] }}"
  loop_control:
    loop_var: "X_ROLE_NAME_X___prepare_path"
...
