---
- name: "Verify"
  hosts: "{{ lookup('env', 'DEVAP_TEST_PLATFORM') | default('all') }}"
  gather_facts: false
  tasks:
    - name: "Load common test vars"
      ansible.builtin.include_vars:
        file: "../test_vars.yml"

    - name: "Discover platform"
      ansible.builtin.setup:
        gather_subset: "min"
        gather_timeout: "10"

    - name: "Load role variables"
      ansible.builtin.include_role:
        public: true
        name: "X_ROLE_NAME_X"

    - name: "Detect target path"
      ansible.builtin.stat:
        path: "{{ X_ROLE_NAME_X_base['run']['X_FILE1_X'] }}"
#        path: "{{ infra_terraform_base['run'][infra_terraform_application['type']]['terraform'] }}"
      register: file_stat

    - name: "Verify app is installed"
      ansible.builtin.assert:
        that:
          - file_stat['stat']['exists']
...
