---
- name: "__TASK_COLLECTION_NAME__ / __TASK_ROLE_NAME__ / Initialize"
  ansible.builtin.include_tasks:
    file: __ROLE_NAME___initialize.yml

- name: "__TASK_COLLECTION_NAME__ / __TASK_ROLE_NAME__ / Deploy"
  ansible.builtin.include_tasks:
    file: __ROLE_NAME___deploy.yml
  when:
    - "'deploy' in __ROLE_NAME__"
    - __ROLE_NAME__['deploy']

- name: "__TASK_COLLECTION_NAME__ / __TASK_ROLE_NAME__ / Finalize"
  include_tasks: __ROLE_NAME___finalize.yml
...
