---
X_ROLE_NAME_X_application:
  name: "X_APP_ID_X"
  type: "X_APP_TYPE_X"
  version: "X_APP_VERSION_X"
  installed: true

X_ROLE_NAME_X_subsystem:
  enabled: false
  status: "stopped"

X_ROLE_NAME_X_server_options:
  X_DEFAULT_SERVER_OPTION_X: "X_DEFAULT_SERVER_OPTION_VALUE_X"

X_ROLE_NAME_X_paths:
  X_DEFAULT_PATH_X: "X_DEFAULT_PATH_VALUE_X"
...
