---
- name: "X_TASK_COLLECTION_NAME_X / X_TASK_ROLE_NAME_X / Prerequisite / Prepare package managers"
  vars:
    sys_repository:
      prepare: true
      deploy: true
      setup: true
      provision: true
    sys_repository_managers:
      flatpak: "{{ X_ROLE_NAME_X_application['type'] == 'flatpak' }}"
      snap: "{{ X_ROLE_NAME_X_application['type'] == 'snap' }}"
      git: "{{ X_ROLE_NAME_X_application['type'] == 'git' }}"
      pip: "{{ X_ROLE_NAME_X_application['type'] == 'pip' }}"
      brew: "{{ X_ROLE_NAME_X_application['type'] == 'brew' }}"
    sys_repository_catalog_distro: "{{ X_ROLE_NAME_X_repository_catalog_distro }}"
    sys_repository_catalog_yum: "{{ X_ROLE_NAME_X_repository_catalog_yum }}"
    sys_repository_catalog_apt: "{{ X_ROLE_NAME_X_repository_catalog_apt }}"
    sys_repository_catalog_brew: "{{ X_ROLE_NAME_X_repository_catalog_brew }}"
    sys_repository_custom_yum: "{{ X_ROLE_NAME_X_repository_custom_yum }}"
    sys_repository_custom_apt: "{{ X_ROLE_NAME_X_repository_custom_apt }}"
    sys_repository_custom_brew: "{{ X_ROLE_NAME_X_repository_custom_brew }}"
  ansible.builtin.include_role:
    name: "serdigital64.system.sys_repository"

- name: "X_TASK_COLLECTION_NAME_X / X_TASK_ROLE_NAME_X / Prerequisite / Prepare archive manager"
  vars:
    bkp_archive:
      deploy: true
  ansible.builtin.include_role:
    name: "serdigital64.backup.bkp_archive"

- name: "X_TASK_COLLECTION_NAME_X / X_TASK_ROLE_NAME_X / Prerequisite / Prepare package installer"
  vars:
    sys_package:
      prepare: true
  ansible.builtin.include_role:
    name: "serdigital64.system.sys_package"
...
