affinity:
  podAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: "X_LABEL_KEY_X"
              operator: "X_AFFINITY_OPERATOR_X"
              values:
                - "X_LABEL_VALUE_X"
        topologyKey: "X_TOPOLOGY_KEY_X"
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: X_AFFINITY_WEIGHT_X
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: "X_LABEL_KEY_X"
                operator: "X_AFFINITY_OPERATOR_X"
                values:
                  - "X_LABEL_VALUE_X"
          topologyKey: "X_TOPOLOGY_KEY_X"
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: "X_LABEL_KEY_X"
              operator: "X_AFFINITY_OPERATOR_X"
              values:
                - "X_LABEL_VALUE_X"
        topologyKey: "X_TOPOLOGY_KEY_X"
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: X_AFFINITY_WEIGHT_X
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: "X_LABEL_KEY_X"
                operator: "X_AFFINITY_OPERATOR_X"
                values:
                  - "X_LABEL_VALUE_X"
          topologyKey: "X_TOPOLOGY_KEY_X"
