# optional ##
# optional ## X_RESOURCE_TYPE_X [/ X_RESOURCE_COMPONENT_X]
# optional ##

# X_TERRAFORM_DATA_PLACEHOLDER_X
data "X_TERRAFORM_DATA_SOURCE_X" "X_TERRAFORM_DATA_NAME_X" {
  # X_TERRAFORM_DATA_CONFIGURATION_PLACEHOLDER_X
}
