---
- name: ""
  ansible.builtin.get_url:
    backup: false
    force: false
    unsafe_writes: false
    timeout: "{{ }}"
    checksum: "{{ }}"
    url: "{{ }}"
    dest: "{{ }}"
    mode: "{{ }}"
    tmp_dest: "{{ }}"
...
