---
- name: ""
  ansible.builtin.file:
    follow: false
    force: false
    unsafe_writes: false
    recurse: false
    state: ~
    path: "{{  }}"
    owner: "{{  }}"
    group: "{{  }}"
    mode: "{{  }}"
    setype: "{{  }}"
...
