- hosts: localhost
  gather_facts: false

  pre_tasks:
    - name: "Include Samples"
      include_vars:
        file: "{{ lookup('env', 'CODESKEL64_SAMPLES') + '/Ansible/vars_dict_01.yml' }}"
    - name: "Include Samples"
      include_vars:
        file: "{{ lookup('env', 'CODESKEL64_SAMPLES') + '/Ansible/vars_dict_02.yml' }}"
    - name: "Include Samples"
      include_vars:
        file: "{{ lookup('env', 'CODESKEL64_SAMPLES') + '/Ansible/vars_dict_03.yml' }}"

  tasks:
    - name: "1.1: Assign dict to dict"
      vars:
        test: "{{ vars_dict_01 }}"
      debug:
        var: test

    - name: "1.2: Assign dict to dict with to_yaml"
      vars:
        test: "{{ vars_dict_01 | to_yaml }}"
      debug:
        var: test

    - name: "1.3: Assign dict to dict with to_nice_yaml"
      vars:
        test: "{{ vars_dict_01 | to_nice_yaml }}"
      debug:
        var: test

    - name: "2.1. Create dynamic dict"
      vars:
        test: "{{
          {
            'key1': 1,
            'key2': 's2',
            'key3': 's3',
            'key4': true
          }
          }}"
      debug:
        var: test

    - name: "2.2. Create dynamic dict"
      vars:
        test: "
          {%- if( 1 == 1 ) -%}
          {{
            {
              'key1': 1,
              'key2': 's2',
              'key3': 's3',
              'key4': true
            }
          }}
          {%- endif -%}
          "
      debug:
        var: test

