---
- name: "Verify"
  hosts: "{{ lookup('env', 'APLATFORM64_TEST_PLATFORM') | default('all') }}"
  gather_facts: false
  tasks:
    - name: "Discover platform"
      ansible.builtin.setup:
        gather_subset: "min"
        gather_timeout: "10"
      changed_when: false

    - name: "Discover packages"
      ansible.builtin.package_facts:
        manager: "auto"

    - name: "Load role variables"
      ansible.builtin.include_role:
        public: true
        name: "X_ROLE_NAME_X"

    - name: "Verify required packages are deployed (package: {{ item }})"
      ansible.builtin.assert:
        that:
          - item['name'] in ansible_facts['packages']
      loop: "{{
        X_ROLE_NAME_X_profiles[
          X_ROLE_NAME_X_application['type']
        ][
          X_ROLE_NAME_X_application['version']
        ]['packages']
        }}"
...
