# optional ##
# optional ## X_RESOURCE_TYPE_X [/ X_RESOURCE_COMPONENT_X]
# optional ##

# X_TERRAFORM_OUTPUTS_PLACEHOLDER_X
output "X_TERRAFORM_OUTPUT_NAME_X" {
  value       = X_TERRAFORM_OUTPUT_VALUE_X
  description = "X_TERRAFORM_OUTPUT_DESCRIPTION_X"
  sensitive   = X_TERRAFORM_OUTPUT_SENSITIVE_X
}
