- hosts: localhost
  gather_facts: false
  vars:
    test_dict:
      key1: 1
      key2: "s2"
      key3: 's3'
  tasks:
    - name: "1.1: Assign dict to dict"
      vars:
        test: "{{ test_dict }}"
      debug:
        var: test['key2']

    - name: "1.2: Assign dict to dict with to_yaml"
      vars:
        test: "{{ test_dict | to_yaml }}"
      debug:
        var: test['key2']

    - name: "1.3: Assign dict to dict with to_nice_yaml"
      vars:
        test: "{{ test_dict | to_nice_yaml }}"
      debug:
        var: test['key2']

    - name: "1.4: Assign dict inline"
      vars:
        test: "{{
          {
            'key1': 1,
            'key2': 's2',
            'key3': 's3'
          }
          }}"
      debug:
        var: test['key2']

    - name: "1.5: Assign dict with code block"
      vars:
        test: "
          {%- if( 1 == 1 ) -%}
          {{
            {
              'key1': 1,
              'key2': 's2',
              'key3': 's3'
            }
          }}
          {%- endif -%}
          "
      debug:
        var: test['key2']

    - name: "2.1: Assign empty list"
      vars:
        test: []
      debug:
        var: test

    - name: "2.2: Assign empty list in quotes"
      vars:
        test: "[]"
      debug:
        var: test

    - name: "2.3: Assign inline list"
      vars:
        test: "[ 1,2,3 ]"
      debug:
        var: test
