---
- name: "X_TASK_COLLECTION_NAME_X / X_TASK_ROLE_NAME_X / Prepare package managers"
  vars:
    core_repository:
      prepare: true
      deploy: true
      setup: true
      provision: true
  ansible.builtin.include_role:
    name: "serdigital64.core.core_repository"

- name: "X_TASK_COLLECTION_NAME_X / X_TASK_ROLE_NAME_X / Prepare package installer"
  vars:
    core_package:
      prepare: true
  ansible.builtin.include_role:
    name: "serdigital64.core.core_package"
...
