# X_TERRAFORM_VARIABLES_PLACEHOLDER_X

# optional ##
# optional ## X_RESOURCE_TYPE_X [/ X_RESOURCE_COMPONENT_X]
# optional ##

variable "X_TERRAFORM_VARIABLE_NAME_X" {
  description = "X_TERRAFORM_VARIABLE_DESCRIPTION_X"
  sensitive   = X_TERRAFORM_VARIABLE_SENSITIVE_X
  nullable    = X_TERRAFORM_VARIABLE_NULLABLE_X
  type        = X_TERRAFORM_VARIABLE_TYPE_X
  default     = X_TERRAFORM_VARIABLE_DEFAULT_X
}
