- hosts: localhost
  gather_facts: false
  tasks:

    - name: "1: Loop dict"
      vars:
        test:
          key1: "value1"
          key2: "value2"
          key3: "value3"
      debug:
        msg: "{{ item }}"
      loop: "{{ lookup( 'dict', test ) }}"

    - name: "2: Loop dict | list"
      vars:
        test:
          key1:
            - "value1"
            - "value2"
          key2:
            - "value3"
      debug:
        msg: "{{ item }}"
      loop: "{{ test | list }}"

    - name: "3: Loop dict | dict2items"
      vars:
        test:
          key1:
            - "value1"
            - "value2"
          key2:
            - "value3"
      debug:
        msg: "{{ item }}"
      loop: "{{ test | dict2items }}"

    - name: "4: Loop dict | list"
      vars:
        test:
          key1: "value1"
          key2: "value2"
      debug:
        msg: "{{ item }}"
      loop: "{{ test | list }}"
