---
# template: 1.1.0
name: "X_WORKFLOW_TITLE_X"

# optional # permissions:
  # X_PERMISSIONS_PLACEHOLDER_X

# optional # concurrency:
  # X_CONCURRENCY_PLACEHOLDER_X

# optional # defaults:
  # X_DEFAULTS_PLACEHOLDER_X

# optional # env:
  # X_WORKFLOW_ENV_PLACEHOLDER_X

on:
  # X_ON_PLACEHOLDER_X

jobs:
  # X_JOB_PLACEHOLDER_X
...
