---
- name: "Converge"
  hosts: "{{ lookup('env', 'DEVAP_TEST_PLATFORM') | default('all') }}"
  gather_facts: false
  tasks:

    - name: "Load common test vars"
      ansible.builtin.include_vars:
        file: "../test_vars.yml"

    - name: "Discover platform"
      ansible.builtin.setup:
        gather_subset: "min"
        gather_timeout: "10"

    - name: "Deploy required packages"
      vars:
        X_ROLE_NAME_X:
          deploy: true
        X_ROLE_NAME_X_application: "{{ test_X_ROLE_NAME_X_application_flatpak }}"
      ansible.builtin.include_role:
        name: "X_ROLE_NAME_X"
...
