---
# Define supported platforms
X_ROLE_NAME_X_platforms:
  - "CentOS8"
  - "OracleLinux8"
  - "Ubuntu20"
  - "Ubuntu21"
  - "Fedora33"
  - "Fedora35"
  - "Debian10"
  - "Debian11"

# Group Linux Distributions by family
X_ROLE_NAME_X_os_family: "
  {%- if
      ( ansible_distribution == 'CentOS' ) or
      ( ansible_distribution == 'OracleLinux' ) or
      ( ansible_distribution == 'Fedora' )
  -%}
    {{ 'RedHat' }}
  {%- elif
      ( ansible_distribution == 'Debian' ) or
      ( ansible_distribution == 'Ubuntu' )
  -%}
    {{ 'Ubuntu' }}
  {%- else -%}
    {{ 'Linux' }}
  {%- endif -%}
  "

# Multiplatform packages
X_ROLE_NAME_X_profiles_common:
  snap: {}
  # snap:
  #   latest:
  #     packages:
  #       - name: "X_APP_PACKAGE_X"
  flatpak: {}
  # flatpak:
  #   latest:
  #     origin: "flathub"
  #     packages:
  #       - name: "X_APP_PACKAGE_X"


# Define default options. Used as a backup for cases where optional Ansible defaults are missing
X_ROLE_NAME_X_presets:
  X_DEFAULT_PATH_X: "X_DEFAULT_PATH_VALUE_X"
  X_PREDEFINED1_X: ""

# Define common paths
X_ROLE_NAME_X_base_common:
  access:
    user:
      owner: "root"
#      X_DEFAULT_USER_X: "{{ X_ROLE_NAME_X_users['X_DEFAULT_USER_X']['name'] }}"
    group:
      owner: "root"
#      X_DEFAULT_USER_X: "{{ X_ROLE_NAME_X_users['X_DEFAULT_USER_X']['group'] }}"
    mode:
      dir: "0755"
      file: "0644"
      exe: "0755"
  templates:
    X_TEMPLATE_SERVER_X: "X_TEMPLATE_SERVER_NAME_X.j2"
  # paths:
  #   X_PATH_X: "{{ X_ROLE_NAME_X_paths['X_DEFAULT_PATH_X'] }}"
  # files:
  #   X_FILE_SERVER_SETUP_X: "X_FILE_SERVER_SETUP_PATH_X"
  # run:
  #   X_COMMAND_X: "X_COMMAND_PATH_X"

X_ROLE_NAME_X_firewall_predefined:
  id: "X_ROLE_NAME_X"

# Temporary loop variables
# X_ROLE_NAME_X___prepare_path: ~
...
