---
# Define platform specific paths
X_ROLE_NAME_X_base:
  # paths: "{{ X_ROLE_NAME_X_base_common['paths'] }}"
  paths:
    X_PATH_X: "{{ X_ROLE_NAME_X_paths['X_DEFAULT_PATH_X'] | default(X_ROLE_NAME_X_presets['X_DEFAULT_PATH_X']) }}"
  # files: "{{ X_ROLE_NAME_X_base_common['files'] }}"
  files:
    X_FILE_SERVER_SETUP_X: "X_FILE_SERVER_SETUP_PATH_X"
  # run: "{{ X_ROLE_NAME_X_base_common['run'] }}"
  run:
    X_COMMAND_X: "X_COMMAND_PATH_X"
  templates: "{{ X_ROLE_NAME_X_base_common['templates'] }}"
#   access:
#     user:
#       owner: "root"
# #      X_DEFAULT_USER_X: "{{ X_ROLE_NAME_X_users['X_DEFAULT_USER_X']['name'] }}"
#     group:
#       owner: "root"
# #      X_DEFAULT_USER_X: "{{ X_ROLE_NAME_X_users['X_DEFAULT_USER_X']['group'] }}"
#     mode:
#       dir: "0755"
#       file: "0644"
#       exe: "0755"
  access: "{{ X_ROLE_NAME_X_base_common['access'] }}"

# Define application package details
X_ROLE_NAME_X_profiles:
  snap: "{{ X_ROLE_NAME_X_profiles_common['snap'] }}"
  flatpak: "{{ X_ROLE_NAME_X_profiles_common['flatpak'] }}"
  distro:
    X_APP_VERSION_X:
      supported: true
      packages:
        - name: "X_APP_PACKAGE_X"

# Define custom package repositories
X_ROLE_NAME_X_repository_custom_yum: []
X_ROLE_NAME_X_repository_custom_apt: []

# Set package repositories states
X_ROLE_NAME_X_repository_catalog_distro: {}
X_ROLE_NAME_X_repository_catalog_yum: {}
X_ROLE_NAME_X_repository_catalog_apt: {}

# Define OS subsystem states
X_ROLE_NAME_X_subsystem_profile:
  service: "X_SUBSYSTEM_NAME_X"
  states:
    started: "started"
    stopped: "stopped"
    refreshed: "refreshed"
...
