---
extends: default

yaml-files:
  - '*.yml'

rules:
  braces:
    max-spaces-inside: 1
    level: error
  brackets:
    max-spaces-inside: 1
    level: error
  colons:
    max-spaces-before: 0
    max-spaces-after: 1
    level: error
  commas:
    max-spaces-before: 0
    max-spaces-after: -1
    level: error
  comments: disable
  comments-indentation: disable
  document-start:
    present: true
  document-end:
    present: true
  empty-lines:
    max: 1
    level: error
  empty-values:
    forbid-in-block-mappings: true
    forbid-in-flow-mappings: true
  hyphens:
    max-spaces-after: 1
    level: error
  indentation:
    spaces: 2
    indent-sequences: true
    check-multi-line-strings: false
  key-duplicates: enable
  line-length: disable
  new-line-at-end-of-file: disable
  new-lines:
    type: unix
  trailing-spaces: disable
  truthy: disable
...
