---
- hosts: localhost
  gather_facts: false
  pre_tasks:
    - name: Create temporary file
      ansible.builtin.tempfile:
        state: "file"
        suffix: "test.txt"
      register: test
      changed_when: false
    - name: "Populate file ({{ test['path'] }}"
      ansible.builtin.copy:
        mode: "0600"
        dest: "{{ test['path'] }}"
        src: "{{ lookup('env', 'DEVCS64_SAMPLES') + '/Ansible/vars_none_01.yml' }}"
      changed_when: false

  tasks:

    - name: "1: regexp"
      ansible.builtin.lineinfile:
        backup: false
        create: false
        unsafe_writes: false
        path: "{{ test['path'] }}"
        state: "present"
        firstmatch: true
        regexp: "^sample_none: ~$"
        line: "{{ 'sample_none: {{ varx }}' }}"

    - name: "1i: regexp"
      ansible.builtin.lineinfile:
        backup: false
        create: false
        unsafe_writes: false
        path: "{{ test['path'] }}"
        state: "present"
        firstmatch: true
        regexp: "^sample_none: ~$"
        line: "{{ 'sample_none: {{ varx }}' }}"

  post_tasks:
    - name: "Delete temporary file ({{ test['path'] }}"
      ansible.builtin.file:
        state: "absent"
        path: "{{ test['path'] }}"
      changed_when: false
...