- hosts: localhost
  gather_facts: false
  tasks:
    - name: "1. Ansible Version"
      debug:
        msg: "{{ ansible_version }}"

    - name: "2. Ansible User"
      debug:
        msg: "{{ ansible_user }}"
