---
- name: "X_TASK_COLLECTION_NAME_X / X_TASK_ROLE_NAME_X / Setup / Server / Configure daemon"
  become: true
  ansible.builtin.template:
    backup: false
    follow: false
    force: true
    unsafe_writes: false
    owner: "{{ X_ROLE_NAME_X_base['access']['owner'] }}"
    group: "{{ X_ROLE_NAME_X_base['access']['group'] }}"
    mode: "{{ X_ROLE_NAME_X_base['access']['mode']['file'] }}"
    src: "{{ X_ROLE_NAME_X_base['templates']['X_TEMPLATE_SERVER_X'] }}"
    dest: "{{ X_ROLE_NAME_X_base['files']['X_FILE_SERVER_SETUP_X'] }}"
...
