- hosts: localhost
  gather_facts: false
  tasks:
    - name: "1.1. Fake changed"
      debug:
        msg: "changed_when: true"
      changed_when: true
      register: test_result

    - name: "1.1. Registered content"
      debug:
        var: test_result
