---
site_name: "X_PROJECT_NAME_NICE_X"
site_description: "X_PROJECT_INFO_X"
site_author: "X_AUTHOR_ALIAS_X"

site_url: "X_PROJECT_DOC_URL_X"
repo_url: "X_PROJECT_GIT_URL_X"

copyright: "GPL-3.0-or-later"
docs_dir: "../docs"
site_dir: "site"
strict: false

extra:
  analytics:
    provider: "google"
    property: "X_AUTHOR_GA4_TAG_X"

extra_css:
  - "css/pygments-tango.css"

plugins:
  - search:
      lang: en
  - include-markdown:
  - minify:
      minify_html: true
      htmlmin_opts:
          remove_comments: true

theme:
  name: "material"
  features:
    #- navigation.tabs
    - navigation.instant
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - toc.integrate
    - navigation.top

  palette:
      - media: "(prefers-color-scheme: light)"
        scheme: default
        toggle:
          icon: material/toggle-switch-off-outline
          name: Switch to dark mode
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        toggle:
          icon: material/toggle-switch
          name: Switch to light mode
markdown_extensions:
  - toc:
      permalink: true
  - markdown.extensions.abbr:
  - markdown.extensions.admonition:
  - markdown.extensions.attr_list:
  - markdown.extensions.def_list:
  - markdown.extensions.md_in_html:
  - markdown.extensions.footnotes:
  - markdown.extensions.meta:
  - markdown.extensions.tables:
  - pymdownx.betterem:
  - pymdownx.tilde:
  - pymdownx.caret:
  - pymdownx.smartsymbols:
  - pymdownx.escapeall:
  - pymdownx.tasklist:
  - pymdownx.progressbar:
  - pymdownx.mark:
  - pymdownx.striphtml:
  - pymdownx.details:
  - pymdownx.tabbed:
  - pymdownx.saneheaders:
  - pymdownx.inlinehilite:
  - pymdownx.snippets:
  - pymdownx.superfences:
  - pymdownx.highlight:
      guess_lang: false
      use_pygments: true
      linenums: true
      linenums_style: "table"

nav:
  - Home: "index.md"
