---
X_ROLE_NAME_X_platforms:
  - "CentOS8"
  - "OracleLinux8"
  - "Ubuntu20"
  - "Ubuntu21"
  - "Fedora33"

X_ROLE_NAME_X_base:
  run:
    __COMMAND__: "__COMMAND_PATH__"

X_ROLE_NAME_X___initialize_platform: ~
...
