---
# Template Version: 2.0.0
name: "Test / Bash / TestManSH"

on:
  push:
    branches:
      - "feature/*"
      - "develop"
      - "main"

jobs:
  test-batscore:
    runs-on: "ubuntu-latest"
    steps:

      - name: "Check out repository code"
        uses: "actions/checkout@main"

      - name: "Prepare build environment"
        run: "./bin/dev-lib"

      - name: "Run tests"
        shell: 'script -q -e -c "bash {0}"'
        run: "./bin/dev-test"
...
