---
# Template: 1.1.0
name: "Test / Bash / TestManSH"

on:
  push:
    branches:
      - "feature/*"
      - "develop"
      - "main"

jobs:
  test-batscore-alpine-3:
    runs-on: "ubuntu-latest"
    steps:

      - name: "Check out repository code"
        uses: "actions/checkout@main"

      - name: "Prepare build environment"
        run: "./bin/devcs-lib"

      - name: "Build app"
        run: "./bin/devcs-build"

      - name: "Run tests"
        shell: 'script -q -e -c "bash {0}"'
        run: "./lib/testmansh -b -o -e bash-test/alpine-3-bash-test:latest"
...
